-- AUTO-GENERATED by scripts/generate-views.js（勿手改；改 view-manifest.json 后重生成）
-- 幂等：DROP VIEW IF EXISTS + CREATE VIEW；部署后重启 postgrest

DROP VIEW IF EXISTS report_store_sales_drill_v CASCADE;
CREATE VIEW report_store_sales_drill_v AS
  SELECT level, parent_code, target_id, code, name, SUM(sale_amount) AS sale_amount, SUM(sale_profit) AS sale_profit, (SUM(sale_profit) / NULLIF(SUM(sale_amount), 0)) AS margin
  FROM (
    SELECT 'region' AS level, NULL::text AS parent_code, t.id AS target_id, dim.first_level_region AS code, dim.first_level_region AS name, SUM(s.total_sale) AS sale_amount, SUM(s.total_profit) AS sale_profit
    FROM report_daily_sales s
    JOIN dim_branch dim ON s.branch_num = dim.branch_num AND s.system_book_code = dim.system_book_code
    JOIN targets t ON (t.system_book_code = 'ALL' OR s.system_book_code = t.system_book_code)
      AND s.biz_date BETWEEN t.start_date AND t.end_date
    WHERE t.status = 'active' AND is_assessed_war_zone(dim.first_level_region)
    GROUP BY t.id, dim.first_level_region, dim.first_level_region
  ) combined
  GROUP BY level, parent_code, target_id, code, name
UNION ALL
  SELECT level, parent_code, target_id, code, name, SUM(sale_amount) AS sale_amount, SUM(sale_profit) AS sale_profit, (SUM(sale_profit) / NULLIF(SUM(sale_amount), 0)) AS margin
  FROM (
    SELECT 'sub_region' AS level, dim.first_level_region AS parent_code, t.id AS target_id, dim.second_level_region AS code, dim.second_level_region AS name, SUM(s.total_sale) AS sale_amount, SUM(s.total_profit) AS sale_profit
    FROM report_daily_sales s
    JOIN dim_branch dim ON s.branch_num = dim.branch_num AND s.system_book_code = dim.system_book_code
    JOIN targets t ON (t.system_book_code = 'ALL' OR s.system_book_code = t.system_book_code)
      AND s.biz_date BETWEEN t.start_date AND t.end_date
    WHERE t.status = 'active' AND is_assessed_war_zone(dim.first_level_region)
    GROUP BY t.id, dim.first_level_region, dim.second_level_region, dim.second_level_region
  ) combined
  GROUP BY level, parent_code, target_id, code, name
UNION ALL
  SELECT level, parent_code, target_id, code, name, SUM(sale_amount) AS sale_amount, SUM(sale_profit) AS sale_profit, (SUM(sale_profit) / NULLIF(SUM(sale_amount), 0)) AS margin
  FROM (
    SELECT 'store' AS level, dim.second_level_region AS parent_code, t.id AS target_id, dim.branch_num AS code, dim.branch_name AS name, SUM(s.total_sale) AS sale_amount, SUM(s.total_profit) AS sale_profit
    FROM report_daily_sales s
    JOIN dim_branch dim ON s.branch_num = dim.branch_num AND s.system_book_code = dim.system_book_code
    JOIN targets t ON (t.system_book_code = 'ALL' OR s.system_book_code = t.system_book_code)
      AND s.biz_date BETWEEN t.start_date AND t.end_date
    WHERE t.status = 'active' AND is_assessed_war_zone(dim.first_level_region)
    GROUP BY t.id, dim.second_level_region, dim.branch_num, dim.branch_name
  ) combined
  GROUP BY level, parent_code, target_id, code, name;
ALTER VIEW report_store_sales_drill_v OWNER TO postgres;
ALTER VIEW report_store_sales_drill_v SET (security_invoker = true);
GRANT SELECT ON report_store_sales_drill_v TO authenticated, anon;

DROP VIEW IF EXISTS report_store_sales_drill_v_audit;
CREATE VIEW report_store_sales_drill_v_audit AS
  SELECT
    target_id,
    sale_amount_region_total,
    sale_amount_sub_region_total,
    sale_amount_store_total,
    ABS(sale_amount_region_total - sale_amount_sub_region_total) AS sale_amount_region_vs_sub_region_diff,
    ABS(sale_amount_region_total - sale_amount_store_total) AS sale_amount_region_vs_store_diff,
    sale_profit_region_total,
    sale_profit_sub_region_total,
    sale_profit_store_total,
    ABS(sale_profit_region_total - sale_profit_sub_region_total) AS sale_profit_region_vs_sub_region_diff,
    ABS(sale_profit_region_total - sale_profit_store_total) AS sale_profit_region_vs_store_diff
  FROM (
    SELECT
      target_id,
        MAX(CASE WHEN level='region' THEN sale_amount_sum END) AS sale_amount_region_total,
        MAX(CASE WHEN level='sub_region' THEN sale_amount_sum END) AS sale_amount_sub_region_total,
        MAX(CASE WHEN level='store' THEN sale_amount_sum END) AS sale_amount_store_total,
        MAX(CASE WHEN level='region' THEN sale_profit_sum END) AS sale_profit_region_total,
        MAX(CASE WHEN level='sub_region' THEN sale_profit_sum END) AS sale_profit_sub_region_total,
        MAX(CASE WHEN level='store' THEN sale_profit_sum END) AS sale_profit_store_total
    FROM (
      SELECT target_id, level, SUM(sale_amount) AS sale_amount_sum, SUM(sale_profit) AS sale_profit_sum
      FROM report_store_sales_drill_v
      GROUP BY target_id, level
    ) y
    GROUP BY target_id
  ) z;
ALTER VIEW report_store_sales_drill_v_audit SET (security_invoker = true);
GRANT SELECT ON report_store_sales_drill_v_audit TO authenticated, anon;
