-- AUTO-GENERATED by scripts/generate-views.js（勿手改；改 view-manifest.json 后重生成）
-- 幂等：DROP VIEW IF EXISTS + CREATE VIEW；部署后重启 postgrest

DROP VIEW IF EXISTS report_distribution_drill_v CASCADE;
CREATE VIEW report_distribution_drill_v AS
  SELECT level, parent_code, target_id, code, name, SUM(delivery_amount) AS delivery_amount, SUM(wholesale_pp_amount) AS wholesale_pp_amount, (SUM(delivery_amount) + SUM(wholesale_pp_amount)) AS distribution_amount
  FROM (
    SELECT 'region' AS level, NULL::text AS parent_code, t.id AS target_id, dim.first_level_region AS code, dim.first_level_region AS name, SUM(COALESCE(s.out_money, 0)) AS delivery_amount, 0 AS wholesale_pp_amount
    FROM dim_branch dim
    JOIN targets t ON (t.system_book_code = 'ALL' OR dim.system_book_code = t.system_book_code)
    LEFT JOIN report_daily_delivery s ON s.branch_num = dim.branch_num AND s.system_book_code = dim.system_book_code
      AND s.biz_date BETWEEN t.start_date AND t.end_date
    WHERE t.status = 'active' AND is_assessed_war_zone(dim.first_level_region)
    GROUP BY t.id, dim.first_level_region, dim.first_level_region
  UNION ALL
    SELECT 'region' AS level, NULL::text AS parent_code, t.id AS target_id, dim.first_level_region AS code, dim.first_level_region AS name, 0 AS delivery_amount, SUM(COALESCE(s.wholesale_money, 0)) AS wholesale_pp_amount
    FROM dim_branch dim
    JOIN targets t ON (t.system_book_code = 'ALL' OR dim.system_book_code = t.system_book_code)
    LEFT JOIN report_daily_wholesale s ON s.branch_num = dim.branch_num AND s.system_book_code = dim.system_book_code
      AND s.biz_date BETWEEN t.start_date AND t.end_date
      AND s.system_book_code = '64188'
    WHERE t.status = 'active' AND is_assessed_war_zone(dim.first_level_region)
    GROUP BY t.id, dim.first_level_region, dim.first_level_region
  ) combined
  GROUP BY level, parent_code, target_id, code, name
UNION ALL
  SELECT level, parent_code, target_id, code, name, SUM(delivery_amount) AS delivery_amount, SUM(wholesale_pp_amount) AS wholesale_pp_amount, (SUM(delivery_amount) + SUM(wholesale_pp_amount)) AS distribution_amount
  FROM (
    SELECT 'sub_region' AS level, dim.first_level_region AS parent_code, t.id AS target_id, dim.second_level_region AS code, dim.second_level_region AS name, SUM(COALESCE(s.out_money, 0)) AS delivery_amount, 0 AS wholesale_pp_amount
    FROM dim_branch dim
    JOIN targets t ON (t.system_book_code = 'ALL' OR dim.system_book_code = t.system_book_code)
    LEFT JOIN report_daily_delivery s ON s.branch_num = dim.branch_num AND s.system_book_code = dim.system_book_code
      AND s.biz_date BETWEEN t.start_date AND t.end_date
    WHERE t.status = 'active' AND is_assessed_war_zone(dim.first_level_region)
    GROUP BY t.id, dim.first_level_region, dim.second_level_region, dim.second_level_region
  UNION ALL
    SELECT 'sub_region' AS level, dim.first_level_region AS parent_code, t.id AS target_id, dim.second_level_region AS code, dim.second_level_region AS name, 0 AS delivery_amount, SUM(COALESCE(s.wholesale_money, 0)) AS wholesale_pp_amount
    FROM dim_branch dim
    JOIN targets t ON (t.system_book_code = 'ALL' OR dim.system_book_code = t.system_book_code)
    LEFT JOIN report_daily_wholesale s ON s.branch_num = dim.branch_num AND s.system_book_code = dim.system_book_code
      AND s.biz_date BETWEEN t.start_date AND t.end_date
      AND s.system_book_code = '64188'
    WHERE t.status = 'active' AND is_assessed_war_zone(dim.first_level_region)
    GROUP BY t.id, dim.first_level_region, dim.second_level_region, dim.second_level_region
  ) combined
  GROUP BY level, parent_code, target_id, code, name
UNION ALL
  SELECT level, parent_code, target_id, code, name, SUM(delivery_amount) AS delivery_amount, SUM(wholesale_pp_amount) AS wholesale_pp_amount, (SUM(delivery_amount) + SUM(wholesale_pp_amount)) AS distribution_amount
  FROM (
    SELECT 'store' AS level, dim.second_level_region AS parent_code, t.id AS target_id, dim.branch_num AS code, dim.branch_name AS name, SUM(COALESCE(s.out_money, 0)) AS delivery_amount, 0 AS wholesale_pp_amount
    FROM dim_branch dim
    JOIN targets t ON (t.system_book_code = 'ALL' OR dim.system_book_code = t.system_book_code)
    LEFT JOIN report_daily_delivery s ON s.branch_num = dim.branch_num AND s.system_book_code = dim.system_book_code
      AND s.biz_date BETWEEN t.start_date AND t.end_date
    WHERE t.status = 'active' AND is_assessed_war_zone(dim.first_level_region)
    GROUP BY t.id, dim.second_level_region, dim.branch_num, dim.branch_name
  UNION ALL
    SELECT 'store' AS level, dim.second_level_region AS parent_code, t.id AS target_id, dim.branch_num AS code, dim.branch_name AS name, 0 AS delivery_amount, SUM(COALESCE(s.wholesale_money, 0)) AS wholesale_pp_amount
    FROM dim_branch dim
    JOIN targets t ON (t.system_book_code = 'ALL' OR dim.system_book_code = t.system_book_code)
    LEFT JOIN report_daily_wholesale s ON s.branch_num = dim.branch_num AND s.system_book_code = dim.system_book_code
      AND s.biz_date BETWEEN t.start_date AND t.end_date
      AND s.system_book_code = '64188'
    WHERE t.status = 'active' AND is_assessed_war_zone(dim.first_level_region)
    GROUP BY t.id, dim.second_level_region, dim.branch_num, dim.branch_name
  ) combined
  GROUP BY level, parent_code, target_id, code, name;
ALTER VIEW report_distribution_drill_v OWNER TO postgres;
ALTER VIEW report_distribution_drill_v SET (security_invoker = true);
GRANT SELECT ON report_distribution_drill_v TO authenticated, anon;

DROP VIEW IF EXISTS report_distribution_drill_v_audit;
CREATE VIEW report_distribution_drill_v_audit AS
  SELECT
    target_id,
    delivery_amount_region_total,
    delivery_amount_sub_region_total,
    delivery_amount_store_total,
    ABS(delivery_amount_region_total - delivery_amount_sub_region_total) AS delivery_amount_region_vs_sub_region_diff,
    ABS(delivery_amount_region_total - delivery_amount_store_total) AS delivery_amount_region_vs_store_diff,
    wholesale_pp_amount_region_total,
    wholesale_pp_amount_sub_region_total,
    wholesale_pp_amount_store_total,
    ABS(wholesale_pp_amount_region_total - wholesale_pp_amount_sub_region_total) AS wholesale_pp_amount_region_vs_sub_region_diff,
    ABS(wholesale_pp_amount_region_total - wholesale_pp_amount_store_total) AS wholesale_pp_amount_region_vs_store_diff,
    distribution_amount_region_total,
    distribution_amount_sub_region_total,
    distribution_amount_store_total,
    ABS(distribution_amount_region_total - distribution_amount_sub_region_total) AS distribution_amount_region_vs_sub_region_diff,
    ABS(distribution_amount_region_total - distribution_amount_store_total) AS distribution_amount_region_vs_store_diff
  FROM (
    SELECT
      target_id,
        MAX(CASE WHEN level='region' THEN delivery_amount_sum END) AS delivery_amount_region_total,
        MAX(CASE WHEN level='sub_region' THEN delivery_amount_sum END) AS delivery_amount_sub_region_total,
        MAX(CASE WHEN level='store' THEN delivery_amount_sum END) AS delivery_amount_store_total,
        MAX(CASE WHEN level='region' THEN wholesale_pp_amount_sum END) AS wholesale_pp_amount_region_total,
        MAX(CASE WHEN level='sub_region' THEN wholesale_pp_amount_sum END) AS wholesale_pp_amount_sub_region_total,
        MAX(CASE WHEN level='store' THEN wholesale_pp_amount_sum END) AS wholesale_pp_amount_store_total,
        MAX(CASE WHEN level='region' THEN distribution_amount_sum END) AS distribution_amount_region_total,
        MAX(CASE WHEN level='sub_region' THEN distribution_amount_sum END) AS distribution_amount_sub_region_total,
        MAX(CASE WHEN level='store' THEN distribution_amount_sum END) AS distribution_amount_store_total
    FROM (
      SELECT target_id, level, SUM(delivery_amount) AS delivery_amount_sum, SUM(wholesale_pp_amount) AS wholesale_pp_amount_sum, SUM(distribution_amount) AS distribution_amount_sum
      FROM report_distribution_drill_v
      GROUP BY target_id, level
    ) y
    GROUP BY target_id
  ) z;
ALTER VIEW report_distribution_drill_v_audit SET (security_invoker = true);
GRANT SELECT ON report_distribution_drill_v_audit TO authenticated, anon;
